# Generated by Django 5.1 on 2024-11-02 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingprogram',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
