# Generated by Django 5.1 on 2024-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_upcomingprogram_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprogram',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
