# Generated by Django 3.2.12 on 2024-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_auto_20240919_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='List_of_group_members',
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='List_of_group_members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
