# Generated by Django 5.1 on 2024-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_userdetails_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='location',
            field=models.CharField(default='ee', max_length=255),
        ),
    ]
