# Generated by Django 3.2.12 on 2024-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0003_auto_20240919_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='members_18_35',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='members_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='members_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='number_of_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
