# Generated by Django 5.1 on 2024-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0004_groupdetails_userdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='has_passport',
            field=models.BooleanField(default=False),
        ),
    ]
