# Generated by Django 5.1 on 2024-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0005_userdetails_has_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetails',
            name='contact',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
