# Generated by Django 5.1 on 2024-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0006_groupdetails_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetails',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='members_18_35',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='members_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='members_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='name_of_contact_person',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='nature_of_activity',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='number_of_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='ward',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='year_of_registration',
            field=models.IntegerField(default=2024),
        ),
    ]
